exports.fluidDict =
{
    "fluid.bufonsetslice~" : {"shortDesc" : "Spectral difference-based audio buffer slicer.",
                              "longDesc" : "Implements many spectral-based onset detection metrics, most of them taken from the literature.",
                              "takesFFT" : true,
                              "type" : "offline",
                              "attributes" : {"source" : {"name" : "Source Buffer",
                                                          "key" : "source",
                                                          "important" : true,
                                                          "type" : "string",
                                                          "default" : "src",
                                                          "value" : "src",
                                                          "desc" : "The index of the buffer used as the source material to be sliced through novelty identification. The different channels of multichannel buffers will be summed."
                                                         },
                                              "indices" : {"name" : "Index Buffer",
                                                           "key" : "indices",
                                                           "important" : true,
                                                           "type" : "string",
                                                           "default" : "idx",
                                                           "value" : "idx",
                                                           "desc" : "The index of the buffer where the indices (in sample) of the estimated starting points of slices will be written. The first and last points are always the boundary points of the analysis."
                                                          },
                                              "startframe" : {"name" : "Starting Frame",
                                                              "key" : "startframe",
                                                              "important" : false,
                                                              "type" : "int",
                                                              "default" : 0,
                                                              "value" : 0,
                                                              "min" : 0,
                                                              "max" : 1000,
                                                              "desc" : "Where in the source buffer shpuld the process start (in samples)."
                                                          },
                                              "startchan" : {"name" : "Starting Channel",
                                                             "key" : "startchan",
                                                             "important" : false,
                                                             "type" : "int",
                                                             "default" : 0,
                                                             "value" : 0,
                                                             "min" : 0,
                                                             "max" : 1,
                                                             "desc" : "For multichannel sources, which channel should be processed."
                                                          },
                                              "numframes" : {"name" : "Number of Frames",
                                                             "key" : "numframes",
                                                             "important" : false,
                                                             "type" : "int",
                                                             "default" : -1,
                                                             "value" : -1,
                                                             "min" : -1,
                                                             "max" : 1000,
                                                             "desc" : "How many frames should be processed."
                                                          },
                                              "numchans" : {"name" : "Number of Channels",
                                                            "key" : "numchans",
                                                            "important" : false,
                                                            "type" : "int",
                                                            "default" : -1,
                                                            "value" : -1,
                                                            "min" : -1,
                                                            "max" : 1,
                                                            "desc" : "For multichannel sources, how many channels should be summed."
                                                          },
                                              "fftwindow" : {"name" : "FFT Window Size",
                                                             "key" : "fftwindow",
                                                             "important" : false,
                                                             "type" : "droplist",
                                                             "default" : 9,
                                                             "value" : 9,
                                                             "states" : [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384],
                                                             "desc" : "As spectral differencing relies on spectral frames, we need to decide what precision we give it spectrally and temporally, in line with the Gabor Uncertainty principles."
                                                          },
                                              "ffthop" : {"name" : "FFT Hop Size",
                                                          "key" : "ffthop",
                                                          "important" : false,
                                                          "type" : "droplist",
                                                          "default" : 9,
                                                          "value" : 9,
                                                          "states" : [-1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384],
                                                          "desc" : "As spectral differencing relies on spectral frames, we need to move the window forward. Low overlap will create audible artefacts. Typically is half the window size."
                                                         },
                                              "fftsize" : {"name" : "FFT Size",
                                                           "key" : "fftsize",
                                                           "type" : "droplist",
                                                           "important" : false,
                                                           "default" : 10,
                                                           "value" : 10,
                                                           "states" : [-1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384],
                                                           "desc" : "The inner FFT/IFFT size. Should be at least 4 samples long, at least the size of the window, and a power of 2. Making it larger allows an oversampling of the spectral precision."
                                                          },
                                              "fftsettings" : {"name" : "FFT Settings",
                                                               "key" : "fftsettings",
                                                               "important" : false,
                                                               "type" : "list",
                                                               "default" : [1024, 512, 512],
                                                               "value" : [1024, 512, 512],
                                                               "desc" : "FFT settings consist of three numbers representing the window size, hop size and FFT size."
                                                               },
                                              "metric" : {"name" : "Metric",
                                                          "key" : "metric",
                                                          "type" : "droplist",
                                                          "important" : true,
                                                          "default" : 0,
                                                          "value" : 0,
                                                          "statesNames" : ["Energy", "High Frequency Content", "Spectral Flux", "Modified Kullback-Leibler", "Itakura-Saito", "Cosine", "Phase Deviation", "Weighted Phase Deviation", "Complex Domain", "Rectified Complex Domain"],
                                                          "desc" : "The metric used to derive a difference curve between spectral frames."
                                                         },
                                              "threshold" : {"name" : "Threshold",
                                                             "key" : "threshold",
                                                             "important" : true,
                                                             "type" : "float",
                                                             "default" : 0.5,
                                                             "value" : 0.5,
                                                             "min" : 0.0,
                                                             "max" : 1.0,
                                                             "desc" : "The threshold of a new slice. Value ranges are different for each metric, from 0 upwards."
                                                            },
                                              "minslicelength" : {"name" : "Minimum Slice Length",
                                                                  "key" : "minslicelength",
                                                                  "important" : false,
                                                                  "type" : "int",
                                                                  "default" : 2,
                                                                  "value" : 2,
                                                                  "min" : 0,
                                                                  "max" : 10,
                                                                  "desc" : "Minimum length of a slice."
                                                                 },
                                              "filtersize" : {"name" : "Smoothing Filter Size",
                                                              "key" : "filtersize",
                                                              "important" : false,
                                                              "type" : "int",
                                                              "default" : 5,
                                                              "value" : 5,
                                                              "min" : 1,
                                                              "max" : 10,
                                                              "desc" : "The size of a smoothing filter that is applied on the novelty curve. A larger filter size allows for cleaner cuts on very sharp changes."
                                                             },
                                              "framedelta" : {"name" : "Frame Delta",
                                                              "key" : "framedelta",
                                                              "important" : false,
                                                              "type" : "int",
                                                              "default" : 0,
                                                              "value" : 0,
                                                              "min" : 0,
                                                              "max" : 1000,
                                                              "desc" : "For certain metrics (HFC, SpectralFlux, MKL, Cosine), the distance does not have to be computed between consecutive frames. By default (0) it is, otherwise this sets the distance between the comparaison window in samples."
                                                             }
                                              }
                          },
      "fluid.buftransientslice~" : {"shortDesc" : "Buffer-based transient-based slicer.",
                                    "longDesc" : "Transient-based slice extractor on buffers.",
                                    "takesFFT" : false,
                                    "type" : "offline",
                                    "attributes" : {"source" : {"name" : "Source Buffer",
                                                                "key" : "source",
                                                                "important" : true,
                                                                "type" : "string",
                                                                "default" : "src",
                                                                "value" : "src",
                                                                "desc" : "The index of the buffer used as the source material to be sliced through novelty identification. The different channels of multichannel buffers will be summed."
                                                                },
                                                "indices" : {"name" : "Index Buffer",
                                                             "key" : "indices",
                                                             "important" : true,
                                                             "type" : "string",
                                                             "default" : "idx",
                                                             "value" : "idx",
                                                             "desc" : "The index of the buffer where the indices (in sample) of the estimated starting points of slices will be written. The first and last points are always the boundary points of the analysis."
                                                            },
                                                "startframe" : {"name" : "Starting Frame",
                                                                "key" : "startframe",
                                                                "important" : false,
                                                                "type" : "int",
                                                                "default" : 0,
                                                                "value" : 0,
                                                                "min" : 0,
                                                                "max" : 1000,
                                                                "desc" : "Where in the source buffer shpuld the process start (in samples)."
                                                               },
                                                "startchan" : {"name" : "Starting Channel",
                                                               "key" : "startchan",
                                                               "important" : false,
                                                               "type" : "int",
                                                               "default" : 0,
                                                               "value" : 0,
                                                               "min" : 0,
                                                               "max" : 1,
                                                               "desc" : "For multichannel sources, which channel should be processed."
                                                              },
                                                "numframes" : {"name" : "Number of Frames",
                                                               "key" : "numframes",
                                                               "important" : false,
                                                               "type" : "int",
                                                               "default" : -1,
                                                               "value" : -1,
                                                               "min" : -1,
                                                               "max" : 1000,
                                                               "desc" : "How many frames should be processed."
                                                              },
                                                "numchans" : {"name" : "Number of Channels",
                                                              "key" : "numchans",
                                                              "important" : false,
                                                              "type" : "int",
                                                              "default" : -1,
                                                              "value" : -1,
                                                              "min" : -1,
                                                              "max" : 1,
                                                              "desc" : "For multichannel sources, how many channels should be summed."
                                                             },
                                                "minslicelength" : {"name" : "Minimum Slice Length",
                                                                    "key" : "minslicelength",
                                                                    "important" : false,
                                                                    "type" : "int",
                                                                    "default" : 2,
                                                                    "value" : 2,
                                                                    "min" : 1,
                                                                    "max" : 10,
                                                                    "desc" : "Minimum length of a slice."
                                                                   },
                                                "order" : {"name" : "Order",
                                                           "key" : "order",
                                                           "important" : false,
                                                           "type" : "int",
                                                           "default" : 20,
                                                           "value" : 20,
                                                           "min" : 0,
                                                           "max" : 50,
                                                           "desc" : "The order in samples of the impulse response filter used to model the estimated continuous signal. It is how many previous samples are used by the algorithm to predict the next one as reference for the model. The highter the order, the more acurate is its spectral definition, not unlike fft, improving low frequency resolution, but it differs in that it is not connected to its temporal resolution."
                                                          },
                                                "blocksize" : {"name" : "Block Size",
                                                               "key" : "blocksize",
                                                               "important" : false,
                                                               "type" : "int",
                                                               "default" : 256,
                                                               "value" : 256,
                                                               "min" : 4,
                                                               "max" : 1024,
                                                               "desc" : "The size in samples of frame on which the algorithm is operating. High values are more cpu intensive, and also determines the maximum transient size, which will not be allowed to be more than half that length in size."
                                                              },
                                                "padsize" : {"name" : "Pad Size",
                                                             "key" : "padsize",
                                                             "important" : false,
                                                             "type" : "int",
                                                             "default" : 128,
                                                             "value" : 128,
                                                             "min" : 2,
                                                             "max" : 512,
                                                             "desc" : "The size of the handles on each side of the block simply used for analysis purposes and avoiding boundary issues."
                                                            },
                                                "skew" : {"name" : "Skew",
                                                          "key" : "skew",
                                                          "important" : true,
                                                          "type" : "float",
                                                          "default" : 0.0,
                                                          "value" : 0.0,
                                                          "min" : -10,
                                                          "max" : 10,
                                                          "desc" : "The nervousness of the bespoke detection function with values from -10 to 10. It allows to decide how peaks are amplified or smoothed before the thresholding. High values increase the sensitivity to small variations."
                                                         },
                                                "threshfwd" : {"name" : "Forward Threshold",
                                                               "key" : "threshfwd",
                                                               "important" : false,
                                                               "type" : "float",
                                                               "default" : 2.0,
                                                               "value" : 2.0,
                                                               "min" : 0.0,
                                                               "max" : 10.0,
                                                               "desc" : "The threshold of the onset of the smoothed error function. It allows tight start of the identification of the anomaly as it proceeds forward."
                                                              },
                                                "threshback" : {"name" : "Backward Threshold",
                                                                "key" : "threshback",
                                                                "important" : false,
                                                                "type" : "float",
                                                                "default" : 1.1,
                                                                "value" : 1.1,
                                                                "min" : 0.0,
                                                                "max" : 10.00,
                                                                "desc" : "The threshold of the offset of the smoothed error function. As it proceeds backwards in time, it allows tight ending of identification of the anomaly."
                                                               },
                                                "windowsize" : {"name" : "Window Size",
                                                                "key" : "windowsize",
                                                                "important" : true,
                                                                "type" : "int",
                                                                "default" : 14,
                                                                "value" : 14,
                                                                "min" : 1,
                                                                "max" : 50,
                                                                "desc" : "The average window of the error detection function. It needs smoothing as it is very jittery. The longer the window, the less precise, but the less false positives."
                                                               },
                                                "clumplength" : {"name" : "Clump Length",
                                                                 "key" : "clumplength",
                                                                 "important" : false,
                                                                 "type" : "int",
                                                                 "default" : 25,
                                                                 "value" : 25,
                                                                 "min" : 1,
                                                                 "max" : 50,
                                                                 "desc" : "Clumping window length."
                                                                }
                                                }
                            }
}
